apiVersion: v1
name: cert-manager-csi-driver-spiffe
type: application
description: csi-driver-spiffe is a Kubernetes CSI plugin which transparently delivers X.509 SPIFFE SVIDs to pods via cert-manager
home: https://cert-manager.io/docs/projects/csi-driver-spiffe/
maintainers:
  - name: cert-manager-maintainers
    email: cert-manager-maintainers@googlegroups.com
    url: https://cert-manager.io
sources:
- https://github.com/cert-manager/csi-driver-spiffe
appVersion: v0.4.1
version: v0.4.1
