kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "cert-manager-csi-driver-spiffe.labels" . | nindent 4 }}
  name: {{ include "cert-manager-csi-driver-spiffe.name" . }}
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["watch", "create", "delete", "list"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "cert-manager-csi-driver-spiffe.labels" . | nindent 4 }}
  name: {{ include "cert-manager-csi-driver-spiffe.name" . }}-approver
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["list", "watch"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests/status"]
  verbs: ["update"]

{{- if .Values.app.approver.signerName }}
- apiGroups: ["cert-manager.io"]
  resources: ["signers"]
  verbs: ["approve"]
  resourceNames: ["{{.Values.app.approver.signerName}}"]
{{- else }}
- apiGroups: ["cert-manager.io"]
  resources: ["signers"]
  verbs: ["approve"]
{{- end }}
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
